app = 'web-os'
primary_region = 'ewr'
kill_signal = 'SIGINT'
kill_timeout = '1m30s'

[experimental]
auto_rollback = true

[build]

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[http_service.concurrency]
type = 'connections'
hard_limit = 65536
soft_limit = 1024

[[http_service.checks]]
interval = '15s'
timeout = '2s'
grace_period = '5s'

[[services]]
protocol = 'udp'
internal_port = 3478
processes = ['app']

[[services.ports]]
port = 3478

[[vm]]
memory = '2048mb'
cpu_kind = 'performance'
cpus = 4
memory_mb = 2048
