[target.riscv64gc-unknown-none-elf]
runner = [
    "qemu-system-riscv64",
    "-machine",
    "virt,aia=aplic-imsic",
    "-bios",
    "none",
    "-m",
    "512M",
    "-smp",
    "4",
    "-serial",
    "mon:stdio",
    "-nographic",
    "-global",
    "virtio-mmio.force-legacy=false",
    "-drive",
    "file=target/fs.img,if=none,format=raw,id=x0",
    "-device",
    "virtio-blk-device,drive=x0,bus=virtio-mmio-bus.0",
    "-kernel",
]
